# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ortobrace
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Cégünk az Ortobrace gyógyászati segédeszközöket előállító és forgalmazó Kft 1994-ben alakult Budapesten. Fő profilunk gyógyászati segédeszköz gyártás forgalmazás, ortopédia cipő készítése. A gyártás és forgalmazás mellett tervezéssel és fejlesztéssel is foglalkozunk. Célunk a megrendelők, ügyfelek és páciensek megbízható az egyedi igényeit és adottságaikat figyelembe vevő kiszolgálása. Teljesítésünk határideje rövid, a kiszolgálás megbízható. Szakembereink megfelelő végzetségekkel rendelkeznek.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ortobrace.hu" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: ['node_modules','build.js','package.json']